version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "golang/src/metric_registrar_examples"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "java-spring-actuator-metrics-to-structured-logs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "java-spring-security"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "kotlin"
    schedule:
      interval: "weekly"

