name: Go

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: golang/src/metric_registrar_examples/go.mod
      - run: go run github.com/onsi/ginkgo/v2/ginkgo -r --compilers=3 --randomize-all --randomize-suites --fail-on-pending --keep-going --race --trace
        working-directory: golang/src/metric_registrar_examples
      - run: go vet ./...
        working-directory: golang/src/metric_registrar_examples

