name: Java

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: microsoft
      - name: Java converting Spring Actuator Metrics to Structured Logs tests
        run: ./gradlew test
        working-directory: java-spring-actuator-metrics-to-structured-logs
      - name: Java using Spring Security tests
        run: ./gradlew test
        working-directory: java-spring-security
      - name: Kotlin tests
        run: ./gradlew test
        working-directory: kotlin
